### PR TITLE
Update to 2.2.7 and added missing builds

### PR DESCRIPTION
**Pull request by madebr**
Please pull this in a new `testing/2.2.7` branch.

I've based this branch on the `testing/2.2.6` branch. (so github gives a conflict)

### CODE REVIEW

**Comment by piponazo** [comment]
Hi @madebr , sorry for the late response, somehow I missed the notification mail :sweat: . I was going to work in the update to 2.2.7 and then I noticed this PR.

I will create a testing/2.2.7 from your commit and make the needed changes on top of it. Thanks for the contribution!

**Comment by piponazo** [comment]
@madebr I just incorporated your changes (and some others) in my personal fork:

https://github.com/piponazo/conan-expat

From now on, I will push the updates of this package there, since I do not work for the Pix4D organization anymore. That's why I did not get notification about this PR.

**Comment by Croydon** [comment]
> From now on, I will push the updates of this package there, since I do not work for the Pix4D organization anymore.

Does that mean that the official Conan package is unmaintained going forward?

**Comment by piponazo** [comment]
> Does that mean that the official Conan package is unmaintained going forward?

Not at all, I will keep maintaining it. I started this recipe when I was working in that organization, but I was the only one taking care about it. Now I do not have full control over this repository, and for example, I cannot create branches here. That's why I decided to keep working on the recipe on my own fork, where I have full control.

**Comment by Croydon** [comment]
But are you allowed to maintain the Expat:pix4d package which is included in conan-center? https://bintray.com/pix4d/conan/Expat%3Apix4d

**Comment by piponazo** [comment]
I am. I have full control there too ;)

**Comment by wagdav** [comment]
@piponazo  what's the status of this PR? Will you merge it? Thanks!

**Comment by piponazo** [comment]
Hi @wagdav ! If you follow the conversation here you will see that I merged the changes in my personal fork and the binaries are uploaded to the conan-center repository:
https://bintray.com/beta/#/pix4d/conan/Expat:pix4d/2.2.7:stable?tab=overview

You can close this PR if you want to keep track of the changes, or just rely in the version available in my fork that I will probably keep maintaining.

**Comment by wagdav** [comment]
> Hi @wagdav ! If you follow the conversation here you will see that I merged the changes in my personal fork and the binaries are uploaded to the conan-center repository:
> https://bintray.com/beta/#/pix4d/conan/Expat:pix4d/2.2.7:stable?tab=overview
> 
> You can close this PR if you want to keep track of the changes, or just rely in the version available in my fork that I will probably keep maintaining.

OK, thanks!

**Pull request closed without merging**
